// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"signon_demo/internal/dao/internal"
	"signon_demo/internal/model/entity"
)

// internalJwtStorageDao is internal type for wrapping internal DAO implements.
type internalJwtStorageDao = *internal.JwtStorageDao

// jwtStorageDao is the data access object for table jwt_storage.
// You can define custom methods on it to extend its functionality as you wish.
type jwtStorageDao struct {
	internalJwtStorageDao
}

var (
	// JwtStorage is globally public accessible object for table jwt_storage operations.
	JwtStorage = jwtStorageDao{
		internal.NewJwtStorageDao(),
	}
)

// Fill with you ideas below.
func AddJwt(ctx context.Context, jwt entity.JwtStorage)(err error){
	_, err = JwtStorage.Ctx(ctx).Data(jwt).Insert()
	return
}