// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package email

import (
	"signon_demo/api/email"
)

type ControllerV1 struct{}

func NewV1() email.IEmailV1 {
	return &ControllerV1{}
}
