server:
  address:     ":80"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  debug: true
  link: 

redis:
  default:
    address: 127.0.0.1:6379
    db:      0

utility:
  aliyun:  
    accesskeyid:    
    accesskeysecret: 
    signname:        
    templatecode:   
    scheme:          http
    regionid:        cn-hangzhou
  wechat:
    token:    
    appid:     
    appsecret: 
  email:
    host:     smtp.qq.com
    port:     587
    username: 
    password: 
  jwt:
    key:     
    # 持续时间：hour
    duration: 24
  code:
    # 验证码发送限制
    min_limit:  1
    hour_limit: 5
    day_limit:  10