// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package phone

import (
	"signon_demo/api/phone"
)

type ControllerV1 struct{}

func NewV1() phone.IPhoneV1 {
	return &ControllerV1{}
}
